# Generated by Django 6.0.3 on 2026-03-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Укажите электронную почту пользователя", max_length=254, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="ID Telegram-чата для отправки напоминаний",
                max_length=50,
                null=True,
                verbose_name="ID чата Telegram",
            ),
        ),
    ]
