# Generated by Django 6.0.3 on 2026-03-10 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь, создавший привычку",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Приятная привычка, связанная с полезной",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
