# Generated by Django 6.0.3 on 2026-03-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_run",
            field=models.DateField(blank=True, null=True, verbose_name="Дата последнего выполнения"),
        ),
    ]
