# Generated by Django 6.0.3 on 2026-03-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_related_habit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="execution_time",
        ),
    ]
