# Generated by Django 6.0.3 on 2026-03-26 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_remove_habit_execution_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="execution_time",
            field=models.TimeField(
                default=datetime.time(0, 0),
                help_text="Время выполнения привычки (формат HH:MM:SS)",
                verbose_name="Время выполнения",
            ),
            preserve_default=False,
        ),
    ]
